cloudflare/python-cloudflare

CloudFlare/__init__.py, CloudFlare/read_configs.py
If extras are not configured, the code fails in 2 places when trying to read_configs(). This patch skips trying to call .split() on a None object.
=> Process 'extras' only if they are set

CloudFlare/read_configs.py
Fixed empty extras field so now you don't need the cloudflare.cfg file anymore:
Without this fix you always need the .cloudflare/cloudflare.cfg file with the extras field set, even if you don't use it. 
With this fix this isn't necessary anymore and only shell variables are required.
=> Fixed empty extras field

CloudFlare/read_configs.py
I intend to pass in the email and token rather than using environment settings or config files. The config parser was failing due to the missing config file and not properly catching the exception.
Problem code in https://github.com/cloudflare/python-cloudflare/blob/master/CloudFlare/read_configs.py with my notes added:
<pre>
if email is None:
email = config.get('CloudFlare', 'email')
try:
email = re.sub(r"\s+", '', config.get('CloudFlare', 'email'))
except ConfigParser.NoOptionError:
email = None
</pre>
Exception raised, but not caught:
`ConfigParser.NoSectionError: No section: 'CloudFlare'`
Reproduce:
<pre>
>>> import os
>>> import ConfigParser
>>> config = ConfigParser.RawConfigParser()
>>> config.read([
...     '.cloudflare.cfg',
...     os.path.expanduser('~/.cloudflare.cfg'),
... …
=> Fix handling of missing config when passing in email and token.

CloudFlare/read_configs.py
Hello,
The library is unusable without config files ```.cloudflare.cfg``` or ```~/.cloudflare.cfg``` or ```~/.cloudflare/cloudflare.cfg``` due fails to parse missing config file. There is no way for example use email and token in class constructor, due continuing fail to parse missing config file.
Example stacktrace:
```pytb
Traceback (most recent call last):
File "ls.py", line 20, in <module>
main()
File "ls.py", line 5, in main
token='XXX')
File "/tmp/cloudflare-listing/env/local/lib/python2.7/site-packages/CloudFlare/cloudflare.py", line 346, in __init__
[conf_email, conf_token, conf_certtoken, extras] = read_configs()
File "/tmp/cloudflare-listing/env/local/lib/python2.7/site-packages/CloudFlare/read_configs.py", line 45, in read_configs
certtoken = re.sub(r"\s+", '', …
```
=> Fix fail parse config if no section

CloudFlare/api_v4.py, cli4/cli4.py
No more global_pools, origins, notifiers, or maps. Latest API version [here](https://www.cloudflare.com/docs/load-balancing-api-reference-20161220.html). 
* We've simplified our configuration API! There are now only *three* endpoints:
* The "load_balancers" API endpoint on your zone(s) now combines the 'old' Load Balancer, Global Policy and Map into a single configuration.
* The "pools" API endpoint combines the 'old' Pool, Origin and Notifier into a single configuration.
* The "monitors" API endpoint is unchanged: how we monitor your infrastructure is important, and thus we wanted to retain the ability for our customers to update a Monitor (increase the timeout, change the status code, etc.) and have it be immediately reflected wherever it is in-use.
=> Update Load Balancing endpoints to reflect latest API changes

CloudFlare/api_v4.py
added missing settings
cli4 --patch value=on /zones/:identifier/settings/http2
cli4 --patch value=overwrite_header /zones/:identifier/settings/pseudo_ipv4
@mahtin could you add it please?
=> http2 / pseudo ipv4 settings

CloudFlare/__init__.py, CloudFlare/cloudflare.py, CloudFlare/read_configs.py, CloudFlare/utils.py, README.md, README.rst, cli4/__main__.py, cli4/cli4.py, cli4/converters.py, setup.py
This is a refactor of the imports in the CloudFlare library. I was prompted to make these changes when trying to use the cli4 utility with Python 3.5 and it wouldn't run. I have done a quick test with the changes on Python 2.6, 2.7. 3.3, 3.4 and 3.5.
**Improved compatibility**
- Uses absolute imports for Python 3 compatibility.
- ConfigParser has changed name and will now be imported correctly on Python 3. This error was hidden by the \_\_init\_\_.py try-except block.
**Robustness and clear errors**
- Removed the try-except block from \_\_init\_\_.py. This was added in commit 110870b4524cad34f7ddd780d9532f5b3e09d374 on the basis that "python3 does not need the import statement", which I cannot reproduce. If this import statement is removed then cli4 will not work with Python 3. Because …
=> Refactor imports

README.md
Page 0 is the same as page 1. And the way that the page is incremented just before the check to see if you are at the final page causes the loop to exit early. By incrementing at the beginning of the loop you get all pages of data and don't miss the last page.
=> Fix Pagination in example raw code

CloudFlare/api_v4.py
Support added for organization endpoints for managing load balancer resources:
organizations/:organization_identifier/load_balancers/pools
organizations/:organization_identifier/load_balancers/monitors
=> Add support for organizational monitors and pools

README.md, README.rst
The kwarg is actually named `params` but incorrectly written as `param` in the code snippets in the README files.
=> README: Fix typo of kwarg "params" in sample code.

examples/example_update_dynamic_dns.py
In line 106 it should be:
`host_name, zone_name = '.'.join(dns_name.split('.')[:2]), '.'.join(dns_name.split('.')[-2:])`
or else domains such as `a.b.example.com` will fail.
=> Fix a minor bug in examples\example_update_dynamic_dns.py

CloudFlare/api_v4.py
This PR adds support for Secondary DNS Endpoints, and allows users to manage Secondary Cloudflare. e.g:
```python
#!/usr/bin/env python
import sys
import CloudFlare
def main():
zone_name = sys.argv[1]
cf = CloudFlare.CloudFlare()
zone_info = cf.zones.post(data={'jump_start':False, 'name': zone_name})
zone_id = zone_info['id']
r = cf.zones.secondary_dns.post(zone_id, data={
"id" : "269d8f4853475ca241c4e730be286b20",
"name" : "www.example.com.",
"masters" :
[
"23ff594956f20c2a721606e94745a8aa",
"00920f38ce07c2e2f4df50b1f61d4194"
],
"auto_refresh_seconds" : 30
})
exit(0)
if __name__ == '__main__':
main()
```
=> DNS-3431: Support Secondary DNS Endpoints

CloudFlare/cloudflare.py, README.md, README.rst
API Tokens (currently in beta) allow more secure usage as they can limit scope.
Fixes https://github.com/cloudflare/python-cloudflare/issues/74
=> Add support for API Tokens

README.rst
For some reason, `described` was misspelt in only the rst version of README
=> Spelling fix

requirements.txt
It was removed from `setup.py` in 16129a394cdc43e07e67cea9b6c14358311f66f4.
=> Remove logger from requirements.txt

README.md
=> Explain zone lookup behaviour in cli4

examples/example_update_dynamic_dns.py
Previously the program didn't store the state of the Cloudflare proxy setting, always setting it to proxied=False during an update, it would break any web-site/web-app protected behind Cloudflare and expose the origin-server IP instead.
With this commit the script will store the state of the 'proxied' value and restore it during a record update.
=> Keep proxied state during IP-address update

setup.py
"future" is never imported. This was added in commit 81113d1f but seems
the package was unnecessary ever since.
=> setup.py: remove unnecessary dependency on future

CloudFlare/read_configs.py, README.md
Updates all references and usage of environment variables from `CF_`
prefix to `CLOUDFLARE_` should they be present. This follows suit of the
other SDKs and tooling in the Cloudflare ecosystem allowing reuse of
credentials between them all.
A full prefix was chosen to avoid conflicts and potential leaking of
details between other tools that use the `CF_` prefix.
Eventually, we will aim to deprecate the `CF_` lookups entirely but for
now, just prefer them if they are present.
=> update environment variables to be prefixed with `CLOUDFLARE_`

CloudFlare/api_v4.py, CloudFlare/cloudflare.py, examples/example_page_rules.py
The 'Bot Management' API is an undocumented API, but one that can still be called through the use of an API key. 
Weirdly, this API returns a 'null' for errors when success is False - which suggests it may not be completely finished. Either way, adding a check in for NoneTypes on the error case is probably proper (considering it was done above when success is not present - although this assumes success afterwards).
=> Added Bot Management ability and fixed an edge case for the API return

CloudFlare/cloudflare.py
fixed ability to add email-fwdr (there's a type preventing the dash to be properly converted)
here's my code if anyone wants to add an email request validation:
```python
cf = CloudFlare(email=CLOUDFLARE_EMAIL, token=CLOUDFLARE_TOKEN)
cf.add('VOID', "accounts", "email-fwdr")
cf.add('AUTH', "accounts", "email-fwdr", "addresses")
data = json.dumps({"email": email})
cf.accounts.email_fwdr.addresses.post(CLOUDFLARE_ACCOUNT, data=data)
```
=> typo in cloudflare.py when handeling props with dashes (email-fwdr)

CloudFlare/api_decode_from_openapi.py
`CloudFlare.api_decode_from_openapi.py::match_identifier` tries to escape `{` and `}` in the RegEx, but doesn't escape the backslash in the Python string literal. 
This PR just changes the string literal to be a raw string literal by prefixing it with `r` so Python doesn't try to interpret any escape sequences in the string.
=> Make RegEx string a raw string literal

setup.py
When running `pip install cloudflare` on Windows with python 3.11,  throw error:
```
Preparing metadata (setup.py) ... error
error: subprocess-exited-with-error
× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [9 lines of output]
Traceback (most recent call last):
File "<string>", line 2, in <module>
File "<pip-setuptools-caller>", line 34, in <module>
File "C:\Users\Daic\AppData\Local\Temp\pip-install-bhkzeuqm\cloudflare_adb441c38e9e43e48350d8f689fe8bef\setup.py", line 49, in <module>
main()
File "C:\Users\Daic\AppData\Local\Temp\pip-install-bhkzeuqm\cloudflare_adb441c38e9e43e48350d8f689fe8bef\setup.py", line 13, in main
long_description = read_me.read()
^^^^^^^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0x88 in position 16820: illegal multibyte …
```
=> Fix UnicodeDecodeError when installing, Update setup.py

CloudFlare/cloudflare.py, CloudFlare/warning_2_20.py, README.md, cli4/cli4.py
Updates the library to spew out a warning when the client is initialised and when an API call is invoked.
This is intentionally annoying and not scoped to stderr to ensure that if anyone does upgrade, they are quickly notified without any impediments.
This PR should be merged and then version 2.20 release on May 5th 2024.
cc @mahtin
=> output major version release imminent warning
